drop table if exists assignment CASCADE;
drop table if exists employees CASCADE;
drop table if exists tasks CASCADE;

create table assignment
(
    task_id     integer not null,
    employee_id integer not null,
    primary key (employee_id, task_id)
);
create table employees
(
    id            integer generated by default as identity (start with 1),
    first_name    varchar(255),
    last_name     varchar(255),
    supervisor_id integer,
    primary key (id)
);
create table tasks
(
    id              integer generated by default as identity (start with 1),
    comment         varchar(255),
    completion_date timestamp,
    due_date        timestamp,
    name            varchar(255),
    status          varchar(255) not null,
    overdue         boolean,
    primary key (id)
);
alter table assignment
    add constraint FKtjlrhsvtrgri2uj8gwu407l3c foreign key (employee_id) references employees;
alter table assignment
    add constraint FKa2wotauggxl7e6p271pud2v0r foreign key (task_id) references tasks;
alter table employees
    add constraint FK2q9drrvhye5m5ivk5h6re2b4i foreign key (supervisor_id) references employees;
